export const SCENE  = {
    CREATE: "SCENE_CREATE",
    DELETE: "SCENE_DELETE",
    UPDATE: "SCENE_UPDATE",
    MAKE_CURRENT: "SCENE_MAKE_CURRENT",
    CREATE_ACTION: "SCENE_ACTION_CREATE",
    DELETE_ACTION: "SCENE_ACTION_DELETE",
};