export const SCENE  = {
    CREATE: "SCENE_CREATE",
    DELETE: "SCENE_DELETE",
    UPDATE: "SCENE_UPDATE",
    MAKE_CURRENT: "SCENE_MAKE_CURRENT",
    CREATE_ACTION: "SCENE_ACTION_CREATE",
    DELETE_ACTION: "SCENE_ACTION_DELETE",
};


export const APPLICATION = {
    INIT: "APPLICATION_INIT",
    START: "APPLICATION_START_SAGA",
    LOAD: "APPLICATION_LOAD",
    LOGIN: "APPLICATION_LOGIN",
    LOGOUT: "APPLICATION_LOGOUT",
    CHANGE_PAGE: "APPLICATION_CHANGE_PAGE",
};